import Modal from '../ui/modal'
import { useActivateAuthModal, useEnableAuthModal } from '../../lib/utils'

const EnableAuthModal = () => {

  const { isOpen, onClose } = useEnableAuthModal();
  const openActiveAuthModal = useActivateAuthModal();

  return (
    <Modal 
      isOpen={isOpen} 
      onClose={onClose}
      useCloseButton={false}
      title='Enable Authenticator App'
      modalSize='w-[420px]'
    >
      <div className='flex flex-col gap-10'>
        <p className='text-sm lg:text-base'>When enabled, we&apos;ll ask for one-time codes generated by your authenticator app whenever you log in or perform transactions</p>
        <div className="flex items-center justify-between gap-4">
          <button className='w-full h-12 rounded-lg bg-primary text-white' onClick={() => {openActiveAuthModal.onOpen(); onClose()}}>
            Yes
          </button>
          <button className='w-full h-12 rounded-lg border-primary border text-primary' onClick={() =>onClose()}>
            No
          </button>
        </div>
      </div>
    </Modal>
  )
}

export default EnableAuthModal