import Modal from '../ui/modal'
import { useActivateAuthModal, useEnableAuthModal } from '../../lib/utils'
import { useApiConfig } from '../../hooks/api';
import useUserDetails from '../../stores/userStore';
import axios from 'axios';

const EnableAuthModal = () => {

  const { isOpen, onClose } = useEnableAuthModal();
  const openActiveAuthModal = useActivateAuthModal();

  const { setAuthDetails } = useUserDetails();

  const start2FaConfig = useApiConfig({
    method: 'get',
    url: 'two-fact-auth'
  });

  const start2Fa = async () => {
    await axios.request(start2FaConfig)
    .then((response) => {
      if (response && response.status === 200) {
        setAuthDetails(response?.data);
        openActiveAuthModal.onOpen(); 
        onClose();
      }
    }).catch((e) => {
      if (e) {
        console.log(e)
      }
    })
  };

  return (
    <Modal 
      isOpen={isOpen} 
      onClose={onClose}
      useCloseButton={true}
      title='Enable Authenticator App'
      modalSize='md:max-w-[540px] w-full'
    >
      <div className='flex flex-col gap-10'>
        <p className='text-sm lg:text-base'>When enabled, we&apos;ll ask for one-time codes generated by your authenticator app whenever you log in or perform transactions</p>
        <div className="flex items-center justify-between gap-4">
          <button className='w-full h-12 rounded-lg bg-primary text-white' onClick={() => start2Fa()}>
            Yes
          </button>
          <button className='w-full h-12 rounded-lg border-primary border text-primary' onClick={() =>onClose()}>
            No
          </button>
        </div>
      </div>
    </Modal>
  )
}

export default EnableAuthModal